### ISSUE TITLE
自动浇水任务执行失败

### ISSUE THREAD

**Issue by he0119** [he0119/smart-home#43]
```log
[2020-09-12 20:00:00,001: INFO/Beat] Scheduler: Sending due task 自动浇水 (iot.tasks.autowatering)
[2020-09-12 20:00:00,004: INFO/MainProcess] Received task: iot.tasks.autowatering[688782ef-8485-4bd2-a0ed-de46f33d4682]
[2020-09-12 20:01:00,050: ERROR/ForkPoolWorker-2] Task iot.tasks.autowatering[688782ef-8485-4bd2-a0ed-de46f33d4682] raised unexpected: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/iot/tasks.py", line 39, in autowatering
    rainfall = weather_api.rainfall_24h()
  File "/usr/src/app/iot/api.py", line 79, in rainfall_24h
    for i in data:
TypeError: 'NoneType' object is not iterable
```

**Comment by he0119** [comment]
根据文档 <https://docs.celeryproject.org/en/stable/userguide/tasks.html#retrying>
有相关处理出错重试的方法
